const events = [
  {
    id: 1,
    title: "Annual Tech Summit 2024",
    category: "Conference",
    date: "Aug 15",
    location: "Silicon Valley Convention Center",
    imgUrl: "https://images.unsplash.com/photo-1582192730841-2a682d7375f9?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8UGFuZWwlMjBEaXNjdXNzaW9uc3xlbnwwfHwwfHx8MA%3D%3D",
    price: "₹2999",
    description: "Join industry leaders for discussions on the future of technology. Keynote speakers from major tech companies.",
    speakers: 10,
    format: "In-person",
    rating: 4.0,
    duration: "2 days",
    target_audience: "Tech Professionals, Entrepreneurs",
    features: ["Keynote Speeches", "Panel Discussions", "Networking Opportunities"],
  },
  {
    id: 7,
    title: "Art Expo 2024",
    category: "Exhibition",
    date: "May 10",
    location: "Miami Art Museum",
    imgUrl: "https://images.unsplash.com/photo-1503293050619-6048ffad0dc5?q=80&w=3089&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1999",
    description: "Showcase of contemporary art from emerging artists.",
    speakers: 0,
    format: "In-person",
    rating: 4.1,
    duration: "1 day",
    target_audience: "Art Enthusiasts, Collectors",
    features: ["Art Displays", "Artist Meet & Greet", "Workshops"],
  },
  {
    id: 13,
    title: "Startup Business Conference 2024",
    category: "Business",
    date: "Nov 10",
    location: "Austin Convention Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1678453147385-c1d2436a74bf?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3499",
    description: "Empowering entrepreneurs with knowledge and connections.",
    speakers: 12,
    format: "In-person",
    rating: 4.6,
    duration: "2 days",
    target_audience: "Startups, Entrepreneurs",
    features: ["Workshops", "Networking", "Pitch Sessions"],
  },
  {
    id: 19,
    title: "Annual Music Festival 2024",
    category: "Festival",
    date: "Jun 25",
    location: "Coachella Valley",
    imgUrl: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?q=80&w=2500&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹4999",
    description: "Experience live performances from top artists.",
    speakers: 0,
    format: "In-person",
    rating: 4.9,
    duration: "3 days",
    target_audience: "Music Lovers",
    features: ["Live Music", "Food Stalls", "Merchandise"],
  },
  {
    id: 25,
    title: "Health and Wellness Conference 2024",
    category: "Health",
    date: "May 05",
    location: "San Francisco Health Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1663036947585-68594f738f67?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8SGVhbHRoJTIwYW5kJTIwV2VsbG5lc3N8ZW58MHx8MHx8fDA%3D",
    price: "₹2999",
    description: "Learn about the latest health trends and wellness practices.",
    speakers: 10,
    format: "In-person",
    rating: 4.5,
    duration: "2 days",
    target_audience: "Health Enthusiasts",
    features: ["Workshops", "Health Screenings", "Nutrition Talks"],
  },
  {
    id: 2,
    title: "Healthcare Innovations Conference 2024",
    category: "Conference",
    date: "Sep 10",
    location: "Los Angeles Convention Center",
    imgUrl: "https://images.unsplash.com/photo-1520110120835-c96534a4c984?q=80&w=3534&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3499",
    description: "Explore groundbreaking healthcare technologies and practices with leading experts.",
    speakers: 8,
    format: "Hybrid",
    rating: 4.2,
    duration: "3 days",
    target_audience: "Healthcare Professionals",
    features: ["Workshops", "Networking", "Exhibits"],
  },
  {
    id: 3,
    title: "Global Marketing Conference 2024",
    category: "Conference",
    date: "Oct 05",
    location: "New York City",
    imgUrl: "https://images.unsplash.com/photo-1607703703520-bb638e84caf2?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3999",
    description: "Delve into the latest marketing trends and strategies with industry leaders.",
    speakers: 12,
    format: "In-person",
    rating: 3.7,
    duration: "2 days",
    target_audience: "Marketing Professionals",
    features: ["Keynote Speeches", "Case Studies", "Networking Events"],
  },
  {
    id: 4,
    title: "Annual AI Conference 2024",
    category: "Conference",
    date: "Nov 12",
    location: "San Francisco",
    imgUrl: "https://plus.unsplash.com/premium_photo-1679547202671-f9dbbf466db4?q=80&w=3432&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹4999",
    description: "Engage with experts on the latest AI research and applications.",
    speakers: 15,
    format: "In-person",
    rating: 4.7,
    duration: "3 days",
    target_audience: "AI Researchers, Developers",
    features: ["Workshops", "Networking", "Exhibitions"],
  },
  {
    id: 5,
    title: "Cybersecurity Summit 2024",
    category: "Conference",
    date: "Dec 01",
    location: "Washington D.C.",
    imgUrl: "https://images.unsplash.com/photo-1590494165264-1ebe3602eb80?q=80&w=3474&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3499",
    description: "Discover the latest in cybersecurity threats and solutions.",
    speakers: 9,
    format: "In-person",
    rating: 3.3,
    duration: "2 days",
    target_audience: "Security Professionals",
    features: ["Keynotes", "Panel Discussions", "Networking"],
  },
  {
    id: 6,
    title: "Blockchain Technology Conference 2024",
    category: "Conference",
    date: "Jan 20",
    location: "Las Vegas",
    imgUrl: "https://images.unsplash.com/photo-1640161704729-cbe966a08476?q=80&w=3544&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3999",
    description: "Explore the future of blockchain technology with industry experts.",
    speakers: 14,
    format: "In-person",
    rating: 4.6,
    duration: "3 days",
    target_audience: "Developers, Entrepreneurs",
    features: ["Workshops", "Networking", "Case Studies"],
  },
  {
    id: 8,
    title: "Tech Innovations Expo 2024",
    category: "Exhibition",
    date: "Jun 15",
    location: "San Francisco Expo Center",
    imgUrl: "https://img.freepik.com/premium-photo/technology-showcase-branding-showcase-incorporate-logo-into-virtual-reality-experiences-interactive-displays-product-demos_1029473-131943.jpg",
    price: "₹2499",
    description: "Explore the latest technology products and services.",
    speakers: 0,
    format: "In-person",
    rating: 3.7,
    duration: "2 days",
    target_audience: "Tech Professionals, Innovators",
    features: ["Product Demos", "Networking", "Workshops"],
  },
  {
    id: 9,
    title: "Health and Wellness Expo 2024",
    category: "Exhibition",
    date: "Jul 20",
    location: "Chicago Health Center",
    imgUrl: "https://images.unsplash.com/photo-1536064479547-7ee40b74b807?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1999",
    description: "Discover wellness products and services from top brands.",
    speakers: 0,
    format: "In-person",
    rating: 4.6,
    duration: "2 days",
    target_audience: "Health Enthusiasts",
    features: ["Health Screenings", "Workshops", "Product Demos"],
  },
  {
    id: 10,
    title: "Travel and Adventure Expo 2024",
    category: "Exhibition",
    date: "Aug 05",
    location: "Los Angeles Convention Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1661776251302-0ef9c4750ecc?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹2499",
    description: "Experience travel experiences and adventures from around the world.",
    speakers: 0,
    format: "In-person",
    rating: 4.4,
    duration: "2 days",
    target_audience: "Travel Enthusiasts",
    features: ["Travel Talks", "Product Demos", "Networking"],
  },
  {
    id: 11,
    title: "Culinary Arts Exhibition 2024",
    category: "Exhibition",
    date: "Sep 25",
    location: "New York Culinary Institute",
    imgUrl: "https://images.unsplash.com/photo-1717756896292-3201089585f6?q=80&w=3472&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1999",
    description: "Showcasing culinary innovations and tastings.",
    speakers: 0,
    format: "In-person",
    rating: 4.5,
    duration: "1 day",
    target_audience: "Food Enthusiasts, Chefs",
    features: ["Cooking Demos", "Tastings", "Networking"],
  },
  {
    id: 12,
    title: "Fashion and Design Expo 2024",
    category: "Exhibition",
    date: "Oct 30",
    location: "Paris Fashion Week Venue",
    imgUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹2999",
    description: "Discover the latest trends in fashion and design.",
    speakers: 0,
    format: "In-person",
    rating: 4.9,
    duration: "3 days",
    target_audience: "Fashion Designers, Enthusiasts",
    features: ["Runway Shows", "Networking", "Workshops"],
  },
  {
    id: 14,
    title: "Corporate Leadership Summit 2024",
    category: "Business",
    date: "Dec 15",
    location: "Chicago Business Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1723924847971-6f54551115b6?q=80&w=3458&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3999",
    description: "Enhance your leadership skills with top executives.",
    speakers: 10,
    format: "In-person",
    rating: 4.8,
    duration: "2 days",
    target_audience: "Business Leaders",
    features: ["Keynotes", "Networking", "Panel Discussions"],
  },
  {
    id: 15,
    title: "Marketing Mastery Conference 2024",
    category: "Business",
    date: "Jan 10",
    location: "New York Convention Center",
    imgUrl: "https://images.unsplash.com/photo-1550305080-4e029753abcf?q=80&w=3542&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹2999",
    description: "Discover innovative marketing strategies from industry leaders.",
    speakers: 9,
    format: "In-person",
    rating: 4.4,
    duration: "2 days",
    target_audience: "Marketing Professionals",
    features: ["Workshops", "Networking", "Case Studies"],
  },
  {
    id: 16,
    title: "Financial Planning Forum 2024",
    category: "Business",
    date: "Feb 15",
    location: "Los Angeles Financial Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1688821130121-3b2cb9aa6636?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1999",
    description: "Learn from experts on effective financial strategies.",
    speakers: 8,
    format: "In-person",
    rating: 4.5,
    duration: "1 day",
    target_audience: "Finance Professionals",
    features: ["Expert Panels", "Workshops", "Networking"],
  },
  {
    id: 17,
    title: "E-commerce Strategies Conference 2024",
    category: "Business",
    date: "Mar 20",
    location: "San Francisco Expo",
    imgUrl: "https://images.unsplash.com/photo-1688561808434-886a6dd97b8c?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3499",
    description: "Explore e-commerce trends and strategies with experts.",
    speakers: 11,
    format: "In-person",
    rating: 4.6,
    duration: "2 days",
    target_audience: "E-commerce Professionals",
    features: ["Workshops", "Networking", "Exhibits"],
  },
  {
    id: 18,
    title: "Leadership Development Workshop 2024",
    category: "Business",
    date: "Apr 10",
    location: "Dallas Business Hub",
    imgUrl: "https://images.unsplash.com/photo-1683516999927-22f6a77b839e?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹2999",
    description: "Develop essential leadership skills with experienced coaches.",
    speakers: 7,
    format: "In-person",
    rating: 4.7,
    duration: "2 days",
    target_audience: "Emerging Leaders",
    features: ["Hands-on Training", "Networking", "Feedback Sessions"],
  },
  {
    id: 20,
    title: "Food Festival 2024",
    category: "Festival",
    date: "Jul 15",
    location: "New Orleans",
    imgUrl: "https://images.unsplash.com/photo-1560479284-b69bb03b5e39?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1999",
    description: "A celebration of culinary delights from around the world.",
    speakers: 0,
    format: "In-person",
    rating: 4.6,
    duration: "2 days",
    target_audience: "Food Enthusiasts",
    features: ["Tastings", "Cooking Demos", "Live Music"],
  },
  {
    id: 21,
    title: "Cultural Heritage Festival 2024",
    category: "Festival",
    date: "Aug 10",
    location: "New York City",
    imgUrl: "https://images.unsplash.com/photo-1665112028615-7e1c4dca5bd1?q=80&w=3000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹2999",
    description: "Celebrate cultural diversity through music, dance, and art.",
    speakers: 0,
    format: "In-person",
    rating: 4.8,
    duration: "2 days",
    target_audience: "Cultural Enthusiasts",
    features: ["Performances", "Art Exhibits", "Food Stalls"],
  },
  {
    id: 22,
    title: "Annual Film Festival 2024",
    category: "Festival",
    date: "Sep 15",
    location: "Los Angeles",
    imgUrl: "https://images.unsplash.com/photo-1657556215165-3d1b9af18370?q=80&w=3435&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3499",
    description: "Showcasing independent films and filmmakers.",
    speakers: 0,
    format: "In-person",
    rating: 4.7,
    duration: "4 days",
    target_audience: "Film Lovers",
    features: ["Screenings", "Q&A Sessions", "Networking"],
  },
  {
    id: 23,
    title: "Annual Tech and Gaming Festival 2024",
    category: "Festival",
    date: "Oct 20",
    location: "Seattle",
    imgUrl: "https://plus.unsplash.com/premium_photo-1661661369132-ad8a6be9e5f4?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹2999",
    description: "Experience the latest in technology and gaming.",
    speakers: 0,
    format: "In-person",
    rating: 4.5,
    duration: "3 days",
    target_audience: "Tech and Gaming Enthusiasts",
    features: ["Demos", "Competitions", "Panels"],
  },
  {
    id: 24,
    title: "Annual Literature Festival 2024",
    category: "Festival",
    date: "Nov 30",
    location: "Boston Public Library",
    imgUrl: "https://images.unsplash.com/photo-1694180847086-2d1d68ad15f4?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8TGl0ZXJhdHVyZSUyMEZlc3RpdmFsfGVufDB8fDB8fHww",
    price: "₹1999",
    description: "Engage with authors and celebrate literature.",
    speakers: 0,
    format: "In-person",
    rating: 4.6,
    duration: "2 days",
    target_audience: "Literature Lovers",
    features: ["Author Readings", "Workshops", "Networking"],
  },
  {
    id: 26,
    title: "Mental Health Awareness Summit 2024",
    category: "Health",
    date: "Jun 10",
    location: "Chicago Wellness Center",
    imgUrl: "https://images.unsplash.com/photo-1608493830924-ec843d9c98c6?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8TWVudGFsJTIwSGVhbHRofGVufDB8fDB8fHww",
    price: "₹1999",
    description: "Focus on mental health issues and solutions.",
    speakers: 8,
    format: "In-person",
    rating: 4.6,
    duration: "1 day",
    target_audience: "Mental Health Professionals",
    features: ["Panels", "Workshops", "Networking"],
  },
  {
    id: 27,
    title: "Nutrition and Health Symposium 2024",
    category: "Health",
    date: "Jul 20",
    location: "Los Angeles Nutrition Center",
    imgUrl: "https://images.unsplash.com/photo-1705103926164-afbfb9be8ca2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bnV0cml0aW9uYWwlMjBmb29kfGVufDB8fDB8fHww",
    price: "₹2499",
    description: "Explore the latest in nutrition science and health.",
    speakers: 9,
    format: "In-person",
    rating: 4.5,
    duration: "2 days",
    target_audience: "Health Professionals",
    features: ["Workshops", "Nutrition Demos", "Networking"],
  },
  {
    id: 28,
    title: "Fitness and Wellness Expo 2024",
    category: "Health",
    date: "Aug 15",
    location: "Miami Fitness Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1670505062582-fdaa83c23c9e?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Rml0bmVzc3xlbnwwfHwwfHx8MA%3D%3D",
    price: "₹1999",
    description: "Discover the latest fitness trends and equipment.",
    speakers: 7,
    format: "In-person",
    rating: 4.4,
    duration: "2 days",
    target_audience: "Fitness Enthusiasts",
    features: ["Workshops", "Fitness Demos", "Networking"],
  },
  {
    id: 29,
    title: "Holistic Health Conference 2024",
    category: "Health",
    date: "Sep 05",
    location: "New York Holistic Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1667762241847-37471e8c8bc0?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8SGVhbHRofGVufDB8fDB8fHww",
    price: "₹2999",
    description: "Explore holistic approaches to health and wellness.",
    speakers: 10,
    format: "In-person",
    rating: 4.7,
    duration: "2 days",
    target_audience: "Wellness Practitioners",
    features: ["Workshops", "Networking", "Demos"],
  },
  {
    id: 30,
    title: "Women's Health Summit 2024",
    category: "Health",
    date: "Oct 15",
    location: "Washington D.C. Health Center",
    imgUrl: "https://plus.unsplash.com/premium_photo-1661779396815-56fe1ca9877c?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8V29tZW4ncyUyMEhlYWx0aHxlbnwwfHwwfHx8MA%3D%3D",
    price: "₹2499",
    description: "Addressing women's health issues and solutions.",
    speakers: 6,
    format: "In-person",
    rating: 4.5,
    duration: "1 day",
    target_audience: "Women Health Professionals",
    features: ["Keynote Speakers", "Workshops", "Networking"],
  },
];

export default events;